version: '3'

services:
  mysql-service:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=demo
    ports:
      - "3307:3306"
  docker-demo-service:
    image: docker-demo:latest
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - /data/docker-demo
    ports:
      - "8080-8090:8080"